export enum ErrorCode {
  JSON_BAD = 'JSON_BAD',

  OPENAPI_VALIDATION = 'OPENAPI_VALIDATION',

  SERVER = 'SERVER',
  SERVER_OPENAPI_RESPONSE_VALIDATION = 'SERVER_OPENAPI_RESPONSE_VALIDATION',
  NOT_FOUND = 'NOT_FOUND',
}

export type ServerErrorCode =
  | ErrorCode.SERVER
  | ErrorCode.SERVER_OPENAPI_RESPONSE_VALIDATION;
