import Decimal from 'decimal.js';
import { injectable } from 'inversify';
import { iterate } from 'iterare';
import { GuardedMap } from '../lib/map';
import { DeepReadonlyArray, DeepReadonlyGuardedMap } from '../lib/types';
import {
  DiamondClarity,
  DiamondColor,
  DiamondCut,
  DiamondProperties,
} from '../models/diamond';

@injectable()
export class DiamondCalculatorService {
  private readonly cutFactors: DeepReadonlyGuardedMap<DiamondCut, Decimal> =
    getCutFactorsMap();
  private readonly getCalculationTable: DeepReadonlyArray<CalculationTableEntry> =
    getCalculationTable();

  calculatePrice(diamond: DiamondProperties): Decimal {
    const pricesForCaratRange = iterate(this.getCalculationTable).find(
      ({ caratThreshold }) => diamond.carat >= caratThreshold
    )?.priceTable;
    if (!pricesForCaratRange) {
      throw new TypeError(`Prices for carat ${diamond.carat} are not found!`);
    }
    return pricesForCaratRange
      .get(diamond.color)
      .get(diamond.clarity)
      .times(diamond.carat)
      .times(this.cutFactors.get(diamond.cut));
  }
}

function getCutFactorsMap(): GuardedMap<DiamondCut, Decimal> {
  return new GuardedMap([
    [DiamondCut.Cushion, new Decimal('6')],
    [DiamondCut.Radiant, new Decimal('1')],
    [DiamondCut.Princess, new Decimal('9')],
    [DiamondCut.Asscher, new Decimal('1')],
    [DiamondCut.Round, new Decimal('7')],
    [DiamondCut.Heart, new Decimal('9')],
    [DiamondCut.Triliant, new Decimal('5')],
    [DiamondCut.Oval, new Decimal('4')],
    [DiamondCut.Pear, new Decimal('7')],
    [DiamondCut.Emerald, new Decimal('10')],
    [DiamondCut.Marquise, new Decimal('5')],
    [DiamondCut.Baguette, new Decimal('8')],
  ]);
}

interface CalculationTableEntry {
  caratThreshold: Decimal;
  priceTable: DeepReadonlyGuardedMap<
    DiamondColor,
    DeepReadonlyGuardedMap<DiamondClarity, Decimal>
  >;
}

function getCalculationTable(): CalculationTableEntry[] {
  return [
    {
      caratThreshold: new Decimal('0'),
      priceTable: new GuardedMap([
        [
          DiamondColor.D,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('75')],
            [DiamondClarity.IF, new Decimal('144')],
            [DiamondClarity.VVS1, new Decimal('209')],
            [DiamondClarity.VVS2, new Decimal('245')],
            [DiamondClarity.VS1, new Decimal('95')],
            [DiamondClarity.VS2, new Decimal('36')],
            [DiamondClarity.SI1, new Decimal('204')],
            [DiamondClarity.SI2, new Decimal('254')],
            [DiamondClarity.SI3, new Decimal('188')],
            [DiamondClarity.I1, new Decimal('201')],
            [DiamondClarity.I2, new Decimal('229')],
            [DiamondClarity.I3, new Decimal('224')],
          ]),
        ],
        [
          DiamondColor.E,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('19')],
            [DiamondClarity.IF, new Decimal('13')],
            [DiamondClarity.VVS1, new Decimal('210')],
            [DiamondClarity.VVS2, new Decimal('16')],
            [DiamondClarity.VS1, new Decimal('45')],
            [DiamondClarity.VS2, new Decimal('235')],
            [DiamondClarity.SI1, new Decimal('53')],
            [DiamondClarity.SI2, new Decimal('25')],
            [DiamondClarity.SI3, new Decimal('57')],
            [DiamondClarity.I1, new Decimal('149')],
            [DiamondClarity.I2, new Decimal('194')],
            [DiamondClarity.I3, new Decimal('246')],
          ]),
        ],
        [
          DiamondColor.F,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('177')],
            [DiamondClarity.IF, new Decimal('148')],
            [DiamondClarity.VVS1, new Decimal('57')],
            [DiamondClarity.VVS2, new Decimal('223')],
            [DiamondClarity.VS1, new Decimal('231')],
            [DiamondClarity.VS2, new Decimal('107')],
            [DiamondClarity.SI1, new Decimal('109')],
            [DiamondClarity.SI2, new Decimal('73')],
            [DiamondClarity.SI3, new Decimal('66')],
            [DiamondClarity.I1, new Decimal('227')],
            [DiamondClarity.I2, new Decimal('128')],
            [DiamondClarity.I3, new Decimal('241')],
          ]),
        ],
        [
          DiamondColor.G,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('28')],
            [DiamondClarity.IF, new Decimal('97')],
            [DiamondClarity.VVS1, new Decimal('122')],
            [DiamondClarity.VVS2, new Decimal('205')],
            [DiamondClarity.VS1, new Decimal('19')],
            [DiamondClarity.VS2, new Decimal('54')],
            [DiamondClarity.SI1, new Decimal('206')],
            [DiamondClarity.SI2, new Decimal('123')],
            [DiamondClarity.SI3, new Decimal('80')],
            [DiamondClarity.I1, new Decimal('121')],
            [DiamondClarity.I2, new Decimal('212')],
            [DiamondClarity.I3, new Decimal('36')],
          ]),
        ],
        [
          DiamondColor.H,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('206')],
            [DiamondClarity.IF, new Decimal('113')],
            [DiamondClarity.VVS1, new Decimal('15')],
            [DiamondClarity.VVS2, new Decimal('99')],
            [DiamondClarity.VS1, new Decimal('159')],
            [DiamondClarity.VS2, new Decimal('127')],
            [DiamondClarity.SI1, new Decimal('78')],
            [DiamondClarity.SI2, new Decimal('241')],
            [DiamondClarity.SI3, new Decimal('219')],
            [DiamondClarity.I1, new Decimal('119')],
            [DiamondClarity.I2, new Decimal('218')],
            [DiamondClarity.I3, new Decimal('141')],
          ]),
        ],
        [
          DiamondColor.I,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('28')],
            [DiamondClarity.IF, new Decimal('130')],
            [DiamondClarity.VVS1, new Decimal('152')],
            [DiamondClarity.VVS2, new Decimal('201')],
            [DiamondClarity.VS1, new Decimal('69')],
            [DiamondClarity.VS2, new Decimal('150')],
            [DiamondClarity.SI1, new Decimal('174')],
            [DiamondClarity.SI2, new Decimal('40')],
            [DiamondClarity.SI3, new Decimal('226')],
            [DiamondClarity.I1, new Decimal('213')],
            [DiamondClarity.I2, new Decimal('239')],
            [DiamondClarity.I3, new Decimal('47')],
          ]),
        ],
        [
          DiamondColor.J,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('19')],
            [DiamondClarity.IF, new Decimal('244')],
            [DiamondClarity.VVS1, new Decimal('193')],
            [DiamondClarity.VVS2, new Decimal('113')],
            [DiamondClarity.VS1, new Decimal('86')],
            [DiamondClarity.VS2, new Decimal('224')],
            [DiamondClarity.SI1, new Decimal('71')],
            [DiamondClarity.SI2, new Decimal('169')],
            [DiamondClarity.SI3, new Decimal('14')],
            [DiamondClarity.I1, new Decimal('229')],
            [DiamondClarity.I2, new Decimal('6')],
            [DiamondClarity.I3, new Decimal('57')],
          ]),
        ],
        [
          DiamondColor.K,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('33')],
            [DiamondClarity.IF, new Decimal('246')],
            [DiamondClarity.VVS1, new Decimal('17')],
            [DiamondClarity.VVS2, new Decimal('102')],
            [DiamondClarity.VS1, new Decimal('86')],
            [DiamondClarity.VS2, new Decimal('108')],
            [DiamondClarity.SI1, new Decimal('184')],
            [DiamondClarity.SI2, new Decimal('130')],
            [DiamondClarity.SI3, new Decimal('184')],
            [DiamondClarity.I1, new Decimal('218')],
            [DiamondClarity.I2, new Decimal('132')],
            [DiamondClarity.I3, new Decimal('133')],
          ]),
        ],
        [
          DiamondColor.L,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('142')],
            [DiamondClarity.IF, new Decimal('107')],
            [DiamondClarity.VVS1, new Decimal('129')],
            [DiamondClarity.VVS2, new Decimal('10')],
            [DiamondClarity.VS1, new Decimal('166')],
            [DiamondClarity.VS2, new Decimal('208')],
            [DiamondClarity.SI1, new Decimal('16')],
            [DiamondClarity.SI2, new Decimal('23')],
            [DiamondClarity.SI3, new Decimal('211')],
            [DiamondClarity.I1, new Decimal('144')],
            [DiamondClarity.I2, new Decimal('239')],
            [DiamondClarity.I3, new Decimal('76')],
          ]),
        ],
        [
          DiamondColor.M,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('176')],
            [DiamondClarity.IF, new Decimal('77')],
            [DiamondClarity.VVS1, new Decimal('250')],
            [DiamondClarity.VVS2, new Decimal('84')],
            [DiamondClarity.VS1, new Decimal('204')],
            [DiamondClarity.VS2, new Decimal('18')],
            [DiamondClarity.SI1, new Decimal('216')],
            [DiamondClarity.SI2, new Decimal('196')],
            [DiamondClarity.SI3, new Decimal('213')],
            [DiamondClarity.I1, new Decimal('102')],
            [DiamondClarity.I2, new Decimal('99')],
            [DiamondClarity.I3, new Decimal('201')],
          ]),
        ],
        [
          DiamondColor.N,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('256')],
            [DiamondClarity.IF, new Decimal('218')],
            [DiamondClarity.VVS1, new Decimal('27')],
            [DiamondClarity.VVS2, new Decimal('57')],
            [DiamondClarity.VS1, new Decimal('59')],
            [DiamondClarity.VS2, new Decimal('43')],
            [DiamondClarity.SI1, new Decimal('42')],
            [DiamondClarity.SI2, new Decimal('85')],
            [DiamondClarity.SI3, new Decimal('240')],
            [DiamondClarity.I1, new Decimal('158')],
            [DiamondClarity.I2, new Decimal('47')],
            [DiamondClarity.I3, new Decimal('206')],
          ]),
        ],
        [
          DiamondColor.O,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('218')],
            [DiamondClarity.IF, new Decimal('124')],
            [DiamondClarity.VVS1, new Decimal('166')],
            [DiamondClarity.VVS2, new Decimal('40')],
            [DiamondClarity.VS1, new Decimal('151')],
            [DiamondClarity.VS2, new Decimal('116')],
            [DiamondClarity.SI1, new Decimal('255')],
            [DiamondClarity.SI2, new Decimal('148')],
            [DiamondClarity.SI3, new Decimal('229')],
            [DiamondClarity.I1, new Decimal('253')],
            [DiamondClarity.I2, new Decimal('172')],
            [DiamondClarity.I3, new Decimal('197')],
          ]),
        ],
        [
          DiamondColor.P,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('11')],
            [DiamondClarity.IF, new Decimal('100')],
            [DiamondClarity.VVS1, new Decimal('255')],
            [DiamondClarity.VVS2, new Decimal('208')],
            [DiamondClarity.VS1, new Decimal('255')],
            [DiamondClarity.VS2, new Decimal('129')],
            [DiamondClarity.SI1, new Decimal('199')],
            [DiamondClarity.SI2, new Decimal('95')],
            [DiamondClarity.SI3, new Decimal('124')],
            [DiamondClarity.I1, new Decimal('84')],
            [DiamondClarity.I2, new Decimal('172')],
            [DiamondClarity.I3, new Decimal('99')],
          ]),
        ],
        [
          DiamondColor.Q,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('243')],
            [DiamondClarity.IF, new Decimal('14')],
            [DiamondClarity.VVS1, new Decimal('24')],
            [DiamondClarity.VVS2, new Decimal('78')],
            [DiamondClarity.VS1, new Decimal('189')],
            [DiamondClarity.VS2, new Decimal('204')],
            [DiamondClarity.SI1, new Decimal('68')],
            [DiamondClarity.SI2, new Decimal('188')],
            [DiamondClarity.SI3, new Decimal('128')],
            [DiamondClarity.I1, new Decimal('238')],
            [DiamondClarity.I2, new Decimal('140')],
            [DiamondClarity.I3, new Decimal('205')],
          ]),
        ],
        [
          DiamondColor.R,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('127')],
            [DiamondClarity.IF, new Decimal('97')],
            [DiamondClarity.VVS1, new Decimal('210')],
            [DiamondClarity.VVS2, new Decimal('241')],
            [DiamondClarity.VS1, new Decimal('238')],
            [DiamondClarity.VS2, new Decimal('9')],
            [DiamondClarity.SI1, new Decimal('224')],
            [DiamondClarity.SI2, new Decimal('240')],
            [DiamondClarity.SI3, new Decimal('1')],
            [DiamondClarity.I1, new Decimal('189')],
            [DiamondClarity.I2, new Decimal('87')],
            [DiamondClarity.I3, new Decimal('36')],
          ]),
        ],
        [
          DiamondColor.S,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('191')],
            [DiamondClarity.IF, new Decimal('130')],
            [DiamondClarity.VVS1, new Decimal('241')],
            [DiamondClarity.VVS2, new Decimal('250')],
            [DiamondClarity.VS1, new Decimal('230')],
            [DiamondClarity.VS2, new Decimal('214')],
            [DiamondClarity.SI1, new Decimal('134')],
            [DiamondClarity.SI2, new Decimal('208')],
            [DiamondClarity.SI3, new Decimal('192')],
            [DiamondClarity.I1, new Decimal('138')],
            [DiamondClarity.I2, new Decimal('39')],
            [DiamondClarity.I3, new Decimal('45')],
          ]),
        ],
        [
          DiamondColor.T,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('244')],
            [DiamondClarity.IF, new Decimal('72')],
            [DiamondClarity.VVS1, new Decimal('39')],
            [DiamondClarity.VVS2, new Decimal('242')],
            [DiamondClarity.VS1, new Decimal('144')],
            [DiamondClarity.VS2, new Decimal('255')],
            [DiamondClarity.SI1, new Decimal('95')],
            [DiamondClarity.SI2, new Decimal('164')],
            [DiamondClarity.SI3, new Decimal('175')],
            [DiamondClarity.I1, new Decimal('97')],
            [DiamondClarity.I2, new Decimal('239')],
            [DiamondClarity.I3, new Decimal('103')],
          ]),
        ],
        [
          DiamondColor.U,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('121')],
            [DiamondClarity.IF, new Decimal('147')],
            [DiamondClarity.VVS1, new Decimal('161')],
            [DiamondClarity.VVS2, new Decimal('195')],
            [DiamondClarity.VS1, new Decimal('97')],
            [DiamondClarity.VS2, new Decimal('126')],
            [DiamondClarity.SI1, new Decimal('40')],
            [DiamondClarity.SI2, new Decimal('224')],
            [DiamondClarity.SI3, new Decimal('68')],
            [DiamondClarity.I1, new Decimal('6')],
            [DiamondClarity.I2, new Decimal('83')],
            [DiamondClarity.I3, new Decimal('190')],
          ]),
        ],
        [
          DiamondColor.V,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('131')],
            [DiamondClarity.IF, new Decimal('96')],
            [DiamondClarity.VVS1, new Decimal('136')],
            [DiamondClarity.VVS2, new Decimal('36')],
            [DiamondClarity.VS1, new Decimal('39')],
            [DiamondClarity.VS2, new Decimal('125')],
            [DiamondClarity.SI1, new Decimal('233')],
            [DiamondClarity.SI2, new Decimal('94')],
            [DiamondClarity.SI3, new Decimal('149')],
            [DiamondClarity.I1, new Decimal('3')],
            [DiamondClarity.I2, new Decimal('68')],
            [DiamondClarity.I3, new Decimal('9')],
          ]),
        ],
        [
          DiamondColor.W,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('159')],
            [DiamondClarity.IF, new Decimal('14')],
            [DiamondClarity.VVS1, new Decimal('85')],
            [DiamondClarity.VVS2, new Decimal('196')],
            [DiamondClarity.VS1, new Decimal('247')],
            [DiamondClarity.VS2, new Decimal('183')],
            [DiamondClarity.SI1, new Decimal('65')],
            [DiamondClarity.SI2, new Decimal('8')],
            [DiamondClarity.SI3, new Decimal('135')],
            [DiamondClarity.I1, new Decimal('189')],
            [DiamondClarity.I2, new Decimal('169')],
            [DiamondClarity.I3, new Decimal('253')],
          ]),
        ],
        [
          DiamondColor.X,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('100')],
            [DiamondClarity.IF, new Decimal('41')],
            [DiamondClarity.VVS1, new Decimal('51')],
            [DiamondClarity.VVS2, new Decimal('153')],
            [DiamondClarity.VS1, new Decimal('79')],
            [DiamondClarity.VS2, new Decimal('162')],
            [DiamondClarity.SI1, new Decimal('188')],
            [DiamondClarity.SI2, new Decimal('160')],
            [DiamondClarity.SI3, new Decimal('247')],
            [DiamondClarity.I1, new Decimal('63')],
            [DiamondClarity.I2, new Decimal('41')],
            [DiamondClarity.I3, new Decimal('238')],
          ]),
        ],
        [
          DiamondColor.Y,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('88')],
            [DiamondClarity.IF, new Decimal('234')],
            [DiamondClarity.VVS1, new Decimal('209')],
            [DiamondClarity.VVS2, new Decimal('82')],
            [DiamondClarity.VS1, new Decimal('153')],
            [DiamondClarity.VS2, new Decimal('13')],
            [DiamondClarity.SI1, new Decimal('30')],
            [DiamondClarity.SI2, new Decimal('252')],
            [DiamondClarity.SI3, new Decimal('212')],
            [DiamondClarity.I1, new Decimal('125')],
            [DiamondClarity.I2, new Decimal('48')],
            [DiamondClarity.I3, new Decimal('74')],
          ]),
        ],
        [
          DiamondColor.Z,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('238')],
            [DiamondClarity.IF, new Decimal('52')],
            [DiamondClarity.VVS1, new Decimal('31')],
            [DiamondClarity.VVS2, new Decimal('200')],
            [DiamondClarity.VS1, new Decimal('238')],
            [DiamondClarity.VS2, new Decimal('208')],
            [DiamondClarity.SI1, new Decimal('166')],
            [DiamondClarity.SI2, new Decimal('221')],
            [DiamondClarity.SI3, new Decimal('33')],
            [DiamondClarity.I1, new Decimal('231')],
            [DiamondClarity.I2, new Decimal('91')],
            [DiamondClarity.I3, new Decimal('214')],
          ]),
        ],
      ]),
    },
    {
      caratThreshold: new Decimal('0.5'),
      priceTable: new GuardedMap([
        [
          DiamondColor.D,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('60')],
            [DiamondClarity.IF, new Decimal('105')],
            [DiamondClarity.VVS1, new Decimal('51')],
            [DiamondClarity.VVS2, new Decimal('40')],
            [DiamondClarity.VS1, new Decimal('209')],
            [DiamondClarity.VS2, new Decimal('76')],
            [DiamondClarity.SI1, new Decimal('108')],
            [DiamondClarity.SI2, new Decimal('169')],
            [DiamondClarity.SI3, new Decimal('200')],
            [DiamondClarity.I1, new Decimal('240')],
            [DiamondClarity.I2, new Decimal('156')],
            [DiamondClarity.I3, new Decimal('89')],
          ]),
        ],
        [
          DiamondColor.E,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('116')],
            [DiamondClarity.IF, new Decimal('225')],
            [DiamondClarity.VVS1, new Decimal('93')],
            [DiamondClarity.VVS2, new Decimal('192')],
            [DiamondClarity.VS1, new Decimal('177')],
            [DiamondClarity.VS2, new Decimal('124')],
            [DiamondClarity.SI1, new Decimal('250')],
            [DiamondClarity.SI2, new Decimal('39')],
            [DiamondClarity.SI3, new Decimal('107')],
            [DiamondClarity.I1, new Decimal('94')],
            [DiamondClarity.I2, new Decimal('129')],
            [DiamondClarity.I3, new Decimal('142')],
          ]),
        ],
        [
          DiamondColor.F,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('178')],
            [DiamondClarity.IF, new Decimal('15')],
            [DiamondClarity.VVS1, new Decimal('27')],
            [DiamondClarity.VVS2, new Decimal('82')],
            [DiamondClarity.VS1, new Decimal('148')],
            [DiamondClarity.VS2, new Decimal('216')],
            [DiamondClarity.SI1, new Decimal('109')],
            [DiamondClarity.SI2, new Decimal('124')],
            [DiamondClarity.SI3, new Decimal('15')],
            [DiamondClarity.I1, new Decimal('100')],
            [DiamondClarity.I2, new Decimal('76')],
            [DiamondClarity.I3, new Decimal('16')],
          ]),
        ],
        [
          DiamondColor.G,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('201')],
            [DiamondClarity.IF, new Decimal('11')],
            [DiamondClarity.VVS1, new Decimal('60')],
            [DiamondClarity.VVS2, new Decimal('43')],
            [DiamondClarity.VS1, new Decimal('160')],
            [DiamondClarity.VS2, new Decimal('111')],
            [DiamondClarity.SI1, new Decimal('47')],
            [DiamondClarity.SI2, new Decimal('136')],
            [DiamondClarity.SI3, new Decimal('42')],
            [DiamondClarity.I1, new Decimal('191')],
            [DiamondClarity.I2, new Decimal('43')],
            [DiamondClarity.I3, new Decimal('247')],
          ]),
        ],
        [
          DiamondColor.H,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('158')],
            [DiamondClarity.IF, new Decimal('54')],
            [DiamondClarity.VVS1, new Decimal('83')],
            [DiamondClarity.VVS2, new Decimal('95')],
            [DiamondClarity.VS1, new Decimal('124')],
            [DiamondClarity.VS2, new Decimal('199')],
            [DiamondClarity.SI1, new Decimal('252')],
            [DiamondClarity.SI2, new Decimal('10')],
            [DiamondClarity.SI3, new Decimal('88')],
            [DiamondClarity.I1, new Decimal('29')],
            [DiamondClarity.I2, new Decimal('22')],
            [DiamondClarity.I3, new Decimal('121')],
          ]),
        ],
        [
          DiamondColor.I,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('95')],
            [DiamondClarity.IF, new Decimal('11')],
            [DiamondClarity.VVS1, new Decimal('182')],
            [DiamondClarity.VVS2, new Decimal('229')],
            [DiamondClarity.VS1, new Decimal('220')],
            [DiamondClarity.VS2, new Decimal('7')],
            [DiamondClarity.SI1, new Decimal('250')],
            [DiamondClarity.SI2, new Decimal('227')],
            [DiamondClarity.SI3, new Decimal('174')],
            [DiamondClarity.I1, new Decimal('130')],
            [DiamondClarity.I2, new Decimal('25')],
            [DiamondClarity.I3, new Decimal('179')],
          ]),
        ],
        [
          DiamondColor.J,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('88')],
            [DiamondClarity.IF, new Decimal('7')],
            [DiamondClarity.VVS1, new Decimal('128')],
            [DiamondClarity.VVS2, new Decimal('2')],
            [DiamondClarity.VS1, new Decimal('248')],
            [DiamondClarity.VS2, new Decimal('244')],
            [DiamondClarity.SI1, new Decimal('251')],
            [DiamondClarity.SI2, new Decimal('200')],
            [DiamondClarity.SI3, new Decimal('134')],
            [DiamondClarity.I1, new Decimal('112')],
            [DiamondClarity.I2, new Decimal('52')],
            [DiamondClarity.I3, new Decimal('250')],
          ]),
        ],
        [
          DiamondColor.K,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('94')],
            [DiamondClarity.IF, new Decimal('199')],
            [DiamondClarity.VVS1, new Decimal('152')],
            [DiamondClarity.VVS2, new Decimal('205')],
            [DiamondClarity.VS1, new Decimal('127')],
            [DiamondClarity.VS2, new Decimal('8')],
            [DiamondClarity.SI1, new Decimal('160')],
            [DiamondClarity.SI2, new Decimal('203')],
            [DiamondClarity.SI3, new Decimal('55')],
            [DiamondClarity.I1, new Decimal('138')],
            [DiamondClarity.I2, new Decimal('214')],
            [DiamondClarity.I3, new Decimal('212')],
          ]),
        ],
        [
          DiamondColor.L,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('244')],
            [DiamondClarity.IF, new Decimal('97')],
            [DiamondClarity.VVS1, new Decimal('22')],
            [DiamondClarity.VVS2, new Decimal('162')],
            [DiamondClarity.VS1, new Decimal('108')],
            [DiamondClarity.VS2, new Decimal('72')],
            [DiamondClarity.SI1, new Decimal('152')],
            [DiamondClarity.SI2, new Decimal('22')],
            [DiamondClarity.SI3, new Decimal('103')],
            [DiamondClarity.I1, new Decimal('199')],
            [DiamondClarity.I2, new Decimal('27')],
            [DiamondClarity.I3, new Decimal('250')],
          ]),
        ],
        [
          DiamondColor.M,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('52')],
            [DiamondClarity.IF, new Decimal('13')],
            [DiamondClarity.VVS1, new Decimal('170')],
            [DiamondClarity.VVS2, new Decimal('159')],
            [DiamondClarity.VS1, new Decimal('212')],
            [DiamondClarity.VS2, new Decimal('191')],
            [DiamondClarity.SI1, new Decimal('76')],
            [DiamondClarity.SI2, new Decimal('27')],
            [DiamondClarity.SI3, new Decimal('49')],
            [DiamondClarity.I1, new Decimal('47')],
            [DiamondClarity.I2, new Decimal('237')],
            [DiamondClarity.I3, new Decimal('36')],
          ]),
        ],
        [
          DiamondColor.N,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('153')],
            [DiamondClarity.IF, new Decimal('230')],
            [DiamondClarity.VVS1, new Decimal('242')],
            [DiamondClarity.VVS2, new Decimal('37')],
            [DiamondClarity.VS1, new Decimal('24')],
            [DiamondClarity.VS2, new Decimal('99')],
            [DiamondClarity.SI1, new Decimal('36')],
            [DiamondClarity.SI2, new Decimal('40')],
            [DiamondClarity.SI3, new Decimal('141')],
            [DiamondClarity.I1, new Decimal('114')],
            [DiamondClarity.I2, new Decimal('226')],
            [DiamondClarity.I3, new Decimal('91')],
          ]),
        ],
        [
          DiamondColor.O,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('194')],
            [DiamondClarity.IF, new Decimal('11')],
            [DiamondClarity.VVS1, new Decimal('207')],
            [DiamondClarity.VVS2, new Decimal('158')],
            [DiamondClarity.VS1, new Decimal('119')],
            [DiamondClarity.VS2, new Decimal('70')],
            [DiamondClarity.SI1, new Decimal('81')],
            [DiamondClarity.SI2, new Decimal('10')],
            [DiamondClarity.SI3, new Decimal('183')],
            [DiamondClarity.I1, new Decimal('120')],
            [DiamondClarity.I2, new Decimal('106')],
            [DiamondClarity.I3, new Decimal('221')],
          ]),
        ],
        [
          DiamondColor.P,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('215')],
            [DiamondClarity.IF, new Decimal('50')],
            [DiamondClarity.VVS1, new Decimal('86')],
            [DiamondClarity.VVS2, new Decimal('72')],
            [DiamondClarity.VS1, new Decimal('24')],
            [DiamondClarity.VS2, new Decimal('209')],
            [DiamondClarity.SI1, new Decimal('221')],
            [DiamondClarity.SI2, new Decimal('13')],
            [DiamondClarity.SI3, new Decimal('193')],
            [DiamondClarity.I1, new Decimal('79')],
            [DiamondClarity.I2, new Decimal('134')],
            [DiamondClarity.I3, new Decimal('94')],
          ]),
        ],
        [
          DiamondColor.Q,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('58')],
            [DiamondClarity.IF, new Decimal('62')],
            [DiamondClarity.VVS1, new Decimal('249')],
            [DiamondClarity.VVS2, new Decimal('243')],
            [DiamondClarity.VS1, new Decimal('124')],
            [DiamondClarity.VS2, new Decimal('19')],
            [DiamondClarity.SI1, new Decimal('239')],
            [DiamondClarity.SI2, new Decimal('72')],
            [DiamondClarity.SI3, new Decimal('220')],
            [DiamondClarity.I1, new Decimal('97')],
            [DiamondClarity.I2, new Decimal('76')],
            [DiamondClarity.I3, new Decimal('167')],
          ]),
        ],
        [
          DiamondColor.R,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('93')],
            [DiamondClarity.IF, new Decimal('122')],
            [DiamondClarity.VVS1, new Decimal('194')],
            [DiamondClarity.VVS2, new Decimal('159')],
            [DiamondClarity.VS1, new Decimal('163')],
            [DiamondClarity.VS2, new Decimal('191')],
            [DiamondClarity.SI1, new Decimal('203')],
            [DiamondClarity.SI2, new Decimal('118')],
            [DiamondClarity.SI3, new Decimal('242')],
            [DiamondClarity.I1, new Decimal('98')],
            [DiamondClarity.I2, new Decimal('185')],
            [DiamondClarity.I3, new Decimal('181')],
          ]),
        ],
        [
          DiamondColor.S,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('116')],
            [DiamondClarity.IF, new Decimal('254')],
            [DiamondClarity.VVS1, new Decimal('195')],
            [DiamondClarity.VVS2, new Decimal('156')],
            [DiamondClarity.VS1, new Decimal('136')],
            [DiamondClarity.VS2, new Decimal('84')],
            [DiamondClarity.SI1, new Decimal('37')],
            [DiamondClarity.SI2, new Decimal('216')],
            [DiamondClarity.SI3, new Decimal('67')],
            [DiamondClarity.I1, new Decimal('243')],
            [DiamondClarity.I2, new Decimal('138')],
            [DiamondClarity.I3, new Decimal('147')],
          ]),
        ],
        [
          DiamondColor.T,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('220')],
            [DiamondClarity.IF, new Decimal('234')],
            [DiamondClarity.VVS1, new Decimal('115')],
            [DiamondClarity.VVS2, new Decimal('168')],
            [DiamondClarity.VS1, new Decimal('241')],
            [DiamondClarity.VS2, new Decimal('7')],
            [DiamondClarity.SI1, new Decimal('171')],
            [DiamondClarity.SI2, new Decimal('188')],
            [DiamondClarity.SI3, new Decimal('114')],
            [DiamondClarity.I1, new Decimal('65')],
            [DiamondClarity.I2, new Decimal('65')],
            [DiamondClarity.I3, new Decimal('232')],
          ]),
        ],
        [
          DiamondColor.U,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('30')],
            [DiamondClarity.IF, new Decimal('6')],
            [DiamondClarity.VVS1, new Decimal('100')],
            [DiamondClarity.VVS2, new Decimal('74')],
            [DiamondClarity.VS1, new Decimal('171')],
            [DiamondClarity.VS2, new Decimal('180')],
            [DiamondClarity.SI1, new Decimal('242')],
            [DiamondClarity.SI2, new Decimal('148')],
            [DiamondClarity.SI3, new Decimal('72')],
            [DiamondClarity.I1, new Decimal('182')],
            [DiamondClarity.I2, new Decimal('140')],
            [DiamondClarity.I3, new Decimal('38')],
          ]),
        ],
        [
          DiamondColor.V,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('149')],
            [DiamondClarity.IF, new Decimal('143')],
            [DiamondClarity.VVS1, new Decimal('22')],
            [DiamondClarity.VVS2, new Decimal('173')],
            [DiamondClarity.VS1, new Decimal('77')],
            [DiamondClarity.VS2, new Decimal('97')],
            [DiamondClarity.SI1, new Decimal('234')],
            [DiamondClarity.SI2, new Decimal('164')],
            [DiamondClarity.SI3, new Decimal('134')],
            [DiamondClarity.I1, new Decimal('235')],
            [DiamondClarity.I2, new Decimal('73')],
            [DiamondClarity.I3, new Decimal('112')],
          ]),
        ],
        [
          DiamondColor.W,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('123')],
            [DiamondClarity.IF, new Decimal('223')],
            [DiamondClarity.VVS1, new Decimal('171')],
            [DiamondClarity.VVS2, new Decimal('76')],
            [DiamondClarity.VS1, new Decimal('16')],
            [DiamondClarity.VS2, new Decimal('229')],
            [DiamondClarity.SI1, new Decimal('80')],
            [DiamondClarity.SI2, new Decimal('86')],
            [DiamondClarity.SI3, new Decimal('174')],
            [DiamondClarity.I1, new Decimal('216')],
            [DiamondClarity.I2, new Decimal('134')],
            [DiamondClarity.I3, new Decimal('224')],
          ]),
        ],
        [
          DiamondColor.X,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('66')],
            [DiamondClarity.IF, new Decimal('254')],
            [DiamondClarity.VVS1, new Decimal('187')],
            [DiamondClarity.VVS2, new Decimal('130')],
            [DiamondClarity.VS1, new Decimal('227')],
            [DiamondClarity.VS2, new Decimal('116')],
            [DiamondClarity.SI1, new Decimal('212')],
            [DiamondClarity.SI2, new Decimal('118')],
            [DiamondClarity.SI3, new Decimal('173')],
            [DiamondClarity.I1, new Decimal('69')],
            [DiamondClarity.I2, new Decimal('223')],
            [DiamondClarity.I3, new Decimal('160')],
          ]),
        ],
        [
          DiamondColor.Y,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('61')],
            [DiamondClarity.IF, new Decimal('197')],
            [DiamondClarity.VVS1, new Decimal('32')],
            [DiamondClarity.VVS2, new Decimal('127')],
            [DiamondClarity.VS1, new Decimal('84')],
            [DiamondClarity.VS2, new Decimal('70')],
            [DiamondClarity.SI1, new Decimal('59')],
            [DiamondClarity.SI2, new Decimal('243')],
            [DiamondClarity.SI3, new Decimal('235')],
            [DiamondClarity.I1, new Decimal('139')],
            [DiamondClarity.I2, new Decimal('70')],
            [DiamondClarity.I3, new Decimal('94')],
          ]),
        ],
        [
          DiamondColor.Z,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('119')],
            [DiamondClarity.IF, new Decimal('121')],
            [DiamondClarity.VVS1, new Decimal('104')],
            [DiamondClarity.VVS2, new Decimal('216')],
            [DiamondClarity.VS1, new Decimal('203')],
            [DiamondClarity.VS2, new Decimal('117')],
            [DiamondClarity.SI1, new Decimal('195')],
            [DiamondClarity.SI2, new Decimal('225')],
            [DiamondClarity.SI3, new Decimal('42')],
            [DiamondClarity.I1, new Decimal('90')],
            [DiamondClarity.I2, new Decimal('82')],
            [DiamondClarity.I3, new Decimal('95')],
          ]),
        ],
      ]),
    },
    {
      caratThreshold: new Decimal('1'),
      priceTable: new GuardedMap([
        [
          DiamondColor.D,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('242')],
            [DiamondClarity.IF, new Decimal('121')],
            [DiamondClarity.VVS1, new Decimal('153')],
            [DiamondClarity.VVS2, new Decimal('181')],
            [DiamondClarity.VS1, new Decimal('143')],
            [DiamondClarity.VS2, new Decimal('54')],
            [DiamondClarity.SI1, new Decimal('188')],
            [DiamondClarity.SI2, new Decimal('188')],
            [DiamondClarity.SI3, new Decimal('226')],
            [DiamondClarity.I1, new Decimal('178')],
            [DiamondClarity.I2, new Decimal('93')],
            [DiamondClarity.I3, new Decimal('47')],
          ]),
        ],
        [
          DiamondColor.E,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('236')],
            [DiamondClarity.IF, new Decimal('199')],
            [DiamondClarity.VVS1, new Decimal('63')],
            [DiamondClarity.VVS2, new Decimal('213')],
            [DiamondClarity.VS1, new Decimal('230')],
            [DiamondClarity.VS2, new Decimal('218')],
            [DiamondClarity.SI1, new Decimal('234')],
            [DiamondClarity.SI2, new Decimal('111')],
            [DiamondClarity.SI3, new Decimal('147')],
            [DiamondClarity.I1, new Decimal('154')],
            [DiamondClarity.I2, new Decimal('121')],
            [DiamondClarity.I3, new Decimal('159')],
          ]),
        ],
        [
          DiamondColor.F,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('16')],
            [DiamondClarity.IF, new Decimal('203')],
            [DiamondClarity.VVS1, new Decimal('214')],
            [DiamondClarity.VVS2, new Decimal('219')],
            [DiamondClarity.VS1, new Decimal('248')],
            [DiamondClarity.VS2, new Decimal('61')],
            [DiamondClarity.SI1, new Decimal('14')],
            [DiamondClarity.SI2, new Decimal('109')],
            [DiamondClarity.SI3, new Decimal('156')],
            [DiamondClarity.I1, new Decimal('10')],
            [DiamondClarity.I2, new Decimal('66')],
            [DiamondClarity.I3, new Decimal('55')],
          ]),
        ],
        [
          DiamondColor.G,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('198')],
            [DiamondClarity.IF, new Decimal('97')],
            [DiamondClarity.VVS1, new Decimal('70')],
            [DiamondClarity.VVS2, new Decimal('243')],
            [DiamondClarity.VS1, new Decimal('130')],
            [DiamondClarity.VS2, new Decimal('223')],
            [DiamondClarity.SI1, new Decimal('72')],
            [DiamondClarity.SI2, new Decimal('226')],
            [DiamondClarity.SI3, new Decimal('25')],
            [DiamondClarity.I1, new Decimal('108')],
            [DiamondClarity.I2, new Decimal('13')],
            [DiamondClarity.I3, new Decimal('164')],
          ]),
        ],
        [
          DiamondColor.H,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('237')],
            [DiamondClarity.IF, new Decimal('158')],
            [DiamondClarity.VVS1, new Decimal('191')],
            [DiamondClarity.VVS2, new Decimal('32')],
            [DiamondClarity.VS1, new Decimal('25')],
            [DiamondClarity.VS2, new Decimal('27')],
            [DiamondClarity.SI1, new Decimal('100')],
            [DiamondClarity.SI2, new Decimal('69')],
            [DiamondClarity.SI3, new Decimal('186')],
            [DiamondClarity.I1, new Decimal('121')],
            [DiamondClarity.I2, new Decimal('171')],
            [DiamondClarity.I3, new Decimal('79')],
          ]),
        ],
        [
          DiamondColor.I,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('136')],
            [DiamondClarity.IF, new Decimal('75')],
            [DiamondClarity.VVS1, new Decimal('123')],
            [DiamondClarity.VVS2, new Decimal('115')],
            [DiamondClarity.VS1, new Decimal('106')],
            [DiamondClarity.VS2, new Decimal('85')],
            [DiamondClarity.SI1, new Decimal('106')],
            [DiamondClarity.SI2, new Decimal('7')],
            [DiamondClarity.SI3, new Decimal('13')],
            [DiamondClarity.I1, new Decimal('55')],
            [DiamondClarity.I2, new Decimal('201')],
            [DiamondClarity.I3, new Decimal('103')],
          ]),
        ],
        [
          DiamondColor.J,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('218')],
            [DiamondClarity.IF, new Decimal('49')],
            [DiamondClarity.VVS1, new Decimal('223')],
            [DiamondClarity.VVS2, new Decimal('170')],
            [DiamondClarity.VS1, new Decimal('77')],
            [DiamondClarity.VS2, new Decimal('111')],
            [DiamondClarity.SI1, new Decimal('99')],
            [DiamondClarity.SI2, new Decimal('183')],
            [DiamondClarity.SI3, new Decimal('160')],
            [DiamondClarity.I1, new Decimal('114')],
            [DiamondClarity.I2, new Decimal('87')],
            [DiamondClarity.I3, new Decimal('118')],
          ]),
        ],
        [
          DiamondColor.K,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('93')],
            [DiamondClarity.IF, new Decimal('133')],
            [DiamondClarity.VVS1, new Decimal('197')],
            [DiamondClarity.VVS2, new Decimal('248')],
            [DiamondClarity.VS1, new Decimal('216')],
            [DiamondClarity.VS2, new Decimal('209')],
            [DiamondClarity.SI1, new Decimal('2')],
            [DiamondClarity.SI2, new Decimal('168')],
            [DiamondClarity.SI3, new Decimal('104')],
            [DiamondClarity.I1, new Decimal('236')],
            [DiamondClarity.I2, new Decimal('11')],
            [DiamondClarity.I3, new Decimal('40')],
          ]),
        ],
        [
          DiamondColor.L,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('242')],
            [DiamondClarity.IF, new Decimal('109')],
            [DiamondClarity.VVS1, new Decimal('175')],
            [DiamondClarity.VVS2, new Decimal('52')],
            [DiamondClarity.VS1, new Decimal('234')],
            [DiamondClarity.VS2, new Decimal('0')],
            [DiamondClarity.SI1, new Decimal('228')],
            [DiamondClarity.SI2, new Decimal('118')],
            [DiamondClarity.SI3, new Decimal('148')],
            [DiamondClarity.I1, new Decimal('23')],
            [DiamondClarity.I2, new Decimal('217')],
            [DiamondClarity.I3, new Decimal('55')],
          ]),
        ],
        [
          DiamondColor.M,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('195')],
            [DiamondClarity.IF, new Decimal('252')],
            [DiamondClarity.VVS1, new Decimal('26')],
            [DiamondClarity.VVS2, new Decimal('212')],
            [DiamondClarity.VS1, new Decimal('158')],
            [DiamondClarity.VS2, new Decimal('46')],
            [DiamondClarity.SI1, new Decimal('1')],
            [DiamondClarity.SI2, new Decimal('103')],
            [DiamondClarity.SI3, new Decimal('90')],
            [DiamondClarity.I1, new Decimal('170')],
            [DiamondClarity.I2, new Decimal('130')],
            [DiamondClarity.I3, new Decimal('25')],
          ]),
        ],
        [
          DiamondColor.N,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('212')],
            [DiamondClarity.IF, new Decimal('229')],
            [DiamondClarity.VVS1, new Decimal('113')],
            [DiamondClarity.VVS2, new Decimal('91')],
            [DiamondClarity.VS1, new Decimal('76')],
            [DiamondClarity.VS2, new Decimal('8')],
            [DiamondClarity.SI1, new Decimal('72')],
            [DiamondClarity.SI2, new Decimal('131')],
            [DiamondClarity.SI3, new Decimal('214')],
            [DiamondClarity.I1, new Decimal('177')],
            [DiamondClarity.I2, new Decimal('154')],
            [DiamondClarity.I3, new Decimal('74')],
          ]),
        ],
        [
          DiamondColor.O,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('106')],
            [DiamondClarity.IF, new Decimal('177')],
            [DiamondClarity.VVS1, new Decimal('64')],
            [DiamondClarity.VVS2, new Decimal('185')],
            [DiamondClarity.VS1, new Decimal('67')],
            [DiamondClarity.VS2, new Decimal('2')],
            [DiamondClarity.SI1, new Decimal('214')],
            [DiamondClarity.SI2, new Decimal('22')],
            [DiamondClarity.SI3, new Decimal('252')],
            [DiamondClarity.I1, new Decimal('126')],
            [DiamondClarity.I2, new Decimal('204')],
            [DiamondClarity.I3, new Decimal('101')],
          ]),
        ],
        [
          DiamondColor.P,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('136')],
            [DiamondClarity.IF, new Decimal('93')],
            [DiamondClarity.VVS1, new Decimal('2')],
            [DiamondClarity.VVS2, new Decimal('168')],
            [DiamondClarity.VS1, new Decimal('234')],
            [DiamondClarity.VS2, new Decimal('182')],
            [DiamondClarity.SI1, new Decimal('228')],
            [DiamondClarity.SI2, new Decimal('116')],
            [DiamondClarity.SI3, new Decimal('184')],
            [DiamondClarity.I1, new Decimal('172')],
            [DiamondClarity.I2, new Decimal('179')],
            [DiamondClarity.I3, new Decimal('71')],
          ]),
        ],
        [
          DiamondColor.Q,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('172')],
            [DiamondClarity.IF, new Decimal('177')],
            [DiamondClarity.VVS1, new Decimal('54')],
            [DiamondClarity.VVS2, new Decimal('138')],
            [DiamondClarity.VS1, new Decimal('44')],
            [DiamondClarity.VS2, new Decimal('132')],
            [DiamondClarity.SI1, new Decimal('51')],
            [DiamondClarity.SI2, new Decimal('219')],
            [DiamondClarity.SI3, new Decimal('124')],
            [DiamondClarity.I1, new Decimal('15')],
            [DiamondClarity.I2, new Decimal('94')],
            [DiamondClarity.I3, new Decimal('56')],
          ]),
        ],
        [
          DiamondColor.R,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('40')],
            [DiamondClarity.IF, new Decimal('64')],
            [DiamondClarity.VVS1, new Decimal('19')],
            [DiamondClarity.VVS2, new Decimal('251')],
            [DiamondClarity.VS1, new Decimal('103')],
            [DiamondClarity.VS2, new Decimal('246')],
            [DiamondClarity.SI1, new Decimal('225')],
            [DiamondClarity.SI2, new Decimal('88')],
            [DiamondClarity.SI3, new Decimal('32')],
            [DiamondClarity.I1, new Decimal('254')],
            [DiamondClarity.I2, new Decimal('42')],
            [DiamondClarity.I3, new Decimal('201')],
          ]),
        ],
        [
          DiamondColor.S,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('43')],
            [DiamondClarity.IF, new Decimal('76')],
            [DiamondClarity.VVS1, new Decimal('249')],
            [DiamondClarity.VVS2, new Decimal('195')],
            [DiamondClarity.VS1, new Decimal('248')],
            [DiamondClarity.VS2, new Decimal('179')],
            [DiamondClarity.SI1, new Decimal('135')],
            [DiamondClarity.SI2, new Decimal('123')],
            [DiamondClarity.SI3, new Decimal('129')],
            [DiamondClarity.I1, new Decimal('179')],
            [DiamondClarity.I2, new Decimal('114')],
            [DiamondClarity.I3, new Decimal('255')],
          ]),
        ],
        [
          DiamondColor.T,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('85')],
            [DiamondClarity.IF, new Decimal('253')],
            [DiamondClarity.VVS1, new Decimal('1')],
            [DiamondClarity.VVS2, new Decimal('235')],
            [DiamondClarity.VS1, new Decimal('100')],
            [DiamondClarity.VS2, new Decimal('213')],
            [DiamondClarity.SI1, new Decimal('80')],
            [DiamondClarity.SI2, new Decimal('195')],
            [DiamondClarity.SI3, new Decimal('180')],
            [DiamondClarity.I1, new Decimal('232')],
            [DiamondClarity.I2, new Decimal('96')],
            [DiamondClarity.I3, new Decimal('138')],
          ]),
        ],
        [
          DiamondColor.U,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('8')],
            [DiamondClarity.IF, new Decimal('113')],
            [DiamondClarity.VVS1, new Decimal('115')],
            [DiamondClarity.VVS2, new Decimal('70')],
            [DiamondClarity.VS1, new Decimal('124')],
            [DiamondClarity.VS2, new Decimal('167')],
            [DiamondClarity.SI1, new Decimal('220')],
            [DiamondClarity.SI2, new Decimal('181')],
            [DiamondClarity.SI3, new Decimal('23')],
            [DiamondClarity.I1, new Decimal('249')],
            [DiamondClarity.I2, new Decimal('57')],
            [DiamondClarity.I3, new Decimal('109')],
          ]),
        ],
        [
          DiamondColor.V,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('76')],
            [DiamondClarity.IF, new Decimal('48')],
            [DiamondClarity.VVS1, new Decimal('229')],
            [DiamondClarity.VVS2, new Decimal('39')],
            [DiamondClarity.VS1, new Decimal('123')],
            [DiamondClarity.VS2, new Decimal('103')],
            [DiamondClarity.SI1, new Decimal('70')],
            [DiamondClarity.SI2, new Decimal('96')],
            [DiamondClarity.SI3, new Decimal('212')],
            [DiamondClarity.I1, new Decimal('18')],
            [DiamondClarity.I2, new Decimal('51')],
            [DiamondClarity.I3, new Decimal('124')],
          ]),
        ],
        [
          DiamondColor.W,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('43')],
            [DiamondClarity.IF, new Decimal('201')],
            [DiamondClarity.VVS1, new Decimal('15')],
            [DiamondClarity.VVS2, new Decimal('62')],
            [DiamondClarity.VS1, new Decimal('15')],
            [DiamondClarity.VS2, new Decimal('145')],
            [DiamondClarity.SI1, new Decimal('132')],
            [DiamondClarity.SI2, new Decimal('211')],
            [DiamondClarity.SI3, new Decimal('42')],
            [DiamondClarity.I1, new Decimal('161')],
            [DiamondClarity.I2, new Decimal('32')],
            [DiamondClarity.I3, new Decimal('159')],
          ]),
        ],
        [
          DiamondColor.X,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('220')],
            [DiamondClarity.IF, new Decimal('95')],
            [DiamondClarity.VVS1, new Decimal('238')],
            [DiamondClarity.VVS2, new Decimal('97')],
            [DiamondClarity.VS1, new Decimal('79')],
            [DiamondClarity.VS2, new Decimal('180')],
            [DiamondClarity.SI1, new Decimal('32')],
            [DiamondClarity.SI2, new Decimal('229')],
            [DiamondClarity.SI3, new Decimal('32')],
            [DiamondClarity.I1, new Decimal('222')],
            [DiamondClarity.I2, new Decimal('79')],
            [DiamondClarity.I3, new Decimal('71')],
          ]),
        ],
        [
          DiamondColor.Y,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('177')],
            [DiamondClarity.IF, new Decimal('18')],
            [DiamondClarity.VVS1, new Decimal('113')],
            [DiamondClarity.VVS2, new Decimal('49')],
            [DiamondClarity.VS1, new Decimal('244')],
            [DiamondClarity.VS2, new Decimal('97')],
            [DiamondClarity.SI1, new Decimal('22')],
            [DiamondClarity.SI2, new Decimal('120')],
            [DiamondClarity.SI3, new Decimal('67')],
            [DiamondClarity.I1, new Decimal('81')],
            [DiamondClarity.I2, new Decimal('28')],
            [DiamondClarity.I3, new Decimal('207')],
          ]),
        ],
        [
          DiamondColor.Z,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('45')],
            [DiamondClarity.IF, new Decimal('128')],
            [DiamondClarity.VVS1, new Decimal('16')],
            [DiamondClarity.VVS2, new Decimal('99')],
            [DiamondClarity.VS1, new Decimal('220')],
            [DiamondClarity.VS2, new Decimal('225')],
            [DiamondClarity.SI1, new Decimal('104')],
            [DiamondClarity.SI2, new Decimal('150')],
            [DiamondClarity.SI3, new Decimal('94')],
            [DiamondClarity.I1, new Decimal('187')],
            [DiamondClarity.I2, new Decimal('43')],
            [DiamondClarity.I3, new Decimal('59')],
          ]),
        ],
      ]),
    },
    {
      caratThreshold: new Decimal('1.5'),
      priceTable: new GuardedMap([
        [
          DiamondColor.D,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('188')],
            [DiamondClarity.IF, new Decimal('7')],
            [DiamondClarity.VVS1, new Decimal('51')],
            [DiamondClarity.VVS2, new Decimal('10')],
            [DiamondClarity.VS1, new Decimal('239')],
            [DiamondClarity.VS2, new Decimal('172')],
            [DiamondClarity.SI1, new Decimal('7')],
            [DiamondClarity.SI2, new Decimal('101')],
            [DiamondClarity.SI3, new Decimal('54')],
            [DiamondClarity.I1, new Decimal('36')],
            [DiamondClarity.I2, new Decimal('241')],
            [DiamondClarity.I3, new Decimal('235')],
          ]),
        ],
        [
          DiamondColor.E,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('198')],
            [DiamondClarity.IF, new Decimal('126')],
            [DiamondClarity.VVS1, new Decimal('146')],
            [DiamondClarity.VVS2, new Decimal('246')],
            [DiamondClarity.VS1, new Decimal('58')],
            [DiamondClarity.VS2, new Decimal('121')],
            [DiamondClarity.SI1, new Decimal('100')],
            [DiamondClarity.SI2, new Decimal('83')],
            [DiamondClarity.SI3, new Decimal('76')],
            [DiamondClarity.I1, new Decimal('101')],
            [DiamondClarity.I2, new Decimal('63')],
            [DiamondClarity.I3, new Decimal('200')],
          ]),
        ],
        [
          DiamondColor.F,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('182')],
            [DiamondClarity.IF, new Decimal('148')],
            [DiamondClarity.VVS1, new Decimal('190')],
            [DiamondClarity.VVS2, new Decimal('223')],
            [DiamondClarity.VS1, new Decimal('71')],
            [DiamondClarity.VS2, new Decimal('99')],
            [DiamondClarity.SI1, new Decimal('157')],
            [DiamondClarity.SI2, new Decimal('53')],
            [DiamondClarity.SI3, new Decimal('151')],
            [DiamondClarity.I1, new Decimal('144')],
            [DiamondClarity.I2, new Decimal('104')],
            [DiamondClarity.I3, new Decimal('84')],
          ]),
        ],
        [
          DiamondColor.G,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('156')],
            [DiamondClarity.IF, new Decimal('90')],
            [DiamondClarity.VVS1, new Decimal('149')],
            [DiamondClarity.VVS2, new Decimal('21')],
            [DiamondClarity.VS1, new Decimal('221')],
            [DiamondClarity.VS2, new Decimal('99')],
            [DiamondClarity.SI1, new Decimal('82')],
            [DiamondClarity.SI2, new Decimal('204')],
            [DiamondClarity.SI3, new Decimal('129')],
            [DiamondClarity.I1, new Decimal('7')],
            [DiamondClarity.I2, new Decimal('215')],
            [DiamondClarity.I3, new Decimal('11')],
          ]),
        ],
        [
          DiamondColor.H,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('254')],
            [DiamondClarity.IF, new Decimal('220')],
            [DiamondClarity.VVS1, new Decimal('57')],
            [DiamondClarity.VVS2, new Decimal('69')],
            [DiamondClarity.VS1, new Decimal('99')],
            [DiamondClarity.VS2, new Decimal('135')],
            [DiamondClarity.SI1, new Decimal('44')],
            [DiamondClarity.SI2, new Decimal('218')],
            [DiamondClarity.SI3, new Decimal('22')],
            [DiamondClarity.I1, new Decimal('64')],
            [DiamondClarity.I2, new Decimal('54')],
            [DiamondClarity.I3, new Decimal('133')],
          ]),
        ],
        [
          DiamondColor.I,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('116')],
            [DiamondClarity.IF, new Decimal('37')],
            [DiamondClarity.VVS1, new Decimal('43')],
            [DiamondClarity.VVS2, new Decimal('98')],
            [DiamondClarity.VS1, new Decimal('23')],
            [DiamondClarity.VS2, new Decimal('88')],
            [DiamondClarity.SI1, new Decimal('87')],
            [DiamondClarity.SI2, new Decimal('182')],
            [DiamondClarity.SI3, new Decimal('176')],
            [DiamondClarity.I1, new Decimal('210')],
            [DiamondClarity.I2, new Decimal('206')],
            [DiamondClarity.I3, new Decimal('56')],
          ]),
        ],
        [
          DiamondColor.J,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('127')],
            [DiamondClarity.IF, new Decimal('51')],
            [DiamondClarity.VVS1, new Decimal('176')],
            [DiamondClarity.VVS2, new Decimal('164')],
            [DiamondClarity.VS1, new Decimal('62')],
            [DiamondClarity.VS2, new Decimal('166')],
            [DiamondClarity.SI1, new Decimal('157')],
            [DiamondClarity.SI2, new Decimal('102')],
            [DiamondClarity.SI3, new Decimal('66')],
            [DiamondClarity.I1, new Decimal('145')],
            [DiamondClarity.I2, new Decimal('100')],
            [DiamondClarity.I3, new Decimal('50')],
          ]),
        ],
        [
          DiamondColor.K,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('242')],
            [DiamondClarity.IF, new Decimal('64')],
            [DiamondClarity.VVS1, new Decimal('247')],
            [DiamondClarity.VVS2, new Decimal('19')],
            [DiamondClarity.VS1, new Decimal('124')],
            [DiamondClarity.VS2, new Decimal('29')],
            [DiamondClarity.SI1, new Decimal('85')],
            [DiamondClarity.SI2, new Decimal('35')],
            [DiamondClarity.SI3, new Decimal('225')],
            [DiamondClarity.I1, new Decimal('43')],
            [DiamondClarity.I2, new Decimal('181')],
            [DiamondClarity.I3, new Decimal('7')],
          ]),
        ],
        [
          DiamondColor.L,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('77')],
            [DiamondClarity.IF, new Decimal('136')],
            [DiamondClarity.VVS1, new Decimal('60')],
            [DiamondClarity.VVS2, new Decimal('200')],
            [DiamondClarity.VS1, new Decimal('25')],
            [DiamondClarity.VS2, new Decimal('162')],
            [DiamondClarity.SI1, new Decimal('40')],
            [DiamondClarity.SI2, new Decimal('174')],
            [DiamondClarity.SI3, new Decimal('89')],
            [DiamondClarity.I1, new Decimal('137')],
            [DiamondClarity.I2, new Decimal('230')],
            [DiamondClarity.I3, new Decimal('237')],
          ]),
        ],
        [
          DiamondColor.M,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('215')],
            [DiamondClarity.IF, new Decimal('254')],
            [DiamondClarity.VVS1, new Decimal('14')],
            [DiamondClarity.VVS2, new Decimal('186')],
            [DiamondClarity.VS1, new Decimal('4')],
            [DiamondClarity.VS2, new Decimal('244')],
            [DiamondClarity.SI1, new Decimal('234')],
            [DiamondClarity.SI2, new Decimal('41')],
            [DiamondClarity.SI3, new Decimal('121')],
            [DiamondClarity.I1, new Decimal('193')],
            [DiamondClarity.I2, new Decimal('210')],
            [DiamondClarity.I3, new Decimal('54')],
          ]),
        ],
        [
          DiamondColor.N,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('23')],
            [DiamondClarity.IF, new Decimal('242')],
            [DiamondClarity.VVS1, new Decimal('212')],
            [DiamondClarity.VVS2, new Decimal('229')],
            [DiamondClarity.VS1, new Decimal('193')],
            [DiamondClarity.VS2, new Decimal('147')],
            [DiamondClarity.SI1, new Decimal('85')],
            [DiamondClarity.SI2, new Decimal('181')],
            [DiamondClarity.SI3, new Decimal('158')],
            [DiamondClarity.I1, new Decimal('209')],
            [DiamondClarity.I2, new Decimal('37')],
            [DiamondClarity.I3, new Decimal('11')],
          ]),
        ],
        [
          DiamondColor.O,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('15')],
            [DiamondClarity.IF, new Decimal('111')],
            [DiamondClarity.VVS1, new Decimal('28')],
            [DiamondClarity.VVS2, new Decimal('182')],
            [DiamondClarity.VS1, new Decimal('55')],
            [DiamondClarity.VS2, new Decimal('92')],
            [DiamondClarity.SI1, new Decimal('225')],
            [DiamondClarity.SI2, new Decimal('95')],
            [DiamondClarity.SI3, new Decimal('201')],
            [DiamondClarity.I1, new Decimal('52')],
            [DiamondClarity.I2, new Decimal('129')],
            [DiamondClarity.I3, new Decimal('69')],
          ]),
        ],
        [
          DiamondColor.P,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('49')],
            [DiamondClarity.IF, new Decimal('69')],
            [DiamondClarity.VVS1, new Decimal('237')],
            [DiamondClarity.VVS2, new Decimal('112')],
            [DiamondClarity.VS1, new Decimal('41')],
            [DiamondClarity.VS2, new Decimal('214')],
            [DiamondClarity.SI1, new Decimal('224')],
            [DiamondClarity.SI2, new Decimal('8')],
            [DiamondClarity.SI3, new Decimal('143')],
            [DiamondClarity.I1, new Decimal('59')],
            [DiamondClarity.I2, new Decimal('61')],
            [DiamondClarity.I3, new Decimal('24')],
          ]),
        ],
        [
          DiamondColor.Q,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('128')],
            [DiamondClarity.IF, new Decimal('99')],
            [DiamondClarity.VVS1, new Decimal('125')],
            [DiamondClarity.VVS2, new Decimal('46')],
            [DiamondClarity.VS1, new Decimal('115')],
            [DiamondClarity.VS2, new Decimal('108')],
            [DiamondClarity.SI1, new Decimal('146')],
            [DiamondClarity.SI2, new Decimal('38')],
            [DiamondClarity.SI3, new Decimal('91')],
            [DiamondClarity.I1, new Decimal('247')],
            [DiamondClarity.I2, new Decimal('159')],
            [DiamondClarity.I3, new Decimal('82')],
          ]),
        ],
        [
          DiamondColor.R,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('234')],
            [DiamondClarity.IF, new Decimal('135')],
            [DiamondClarity.VVS1, new Decimal('105')],
            [DiamondClarity.VVS2, new Decimal('159')],
            [DiamondClarity.VS1, new Decimal('161')],
            [DiamondClarity.VS2, new Decimal('256')],
            [DiamondClarity.SI1, new Decimal('113')],
            [DiamondClarity.SI2, new Decimal('112')],
            [DiamondClarity.SI3, new Decimal('58')],
            [DiamondClarity.I1, new Decimal('231')],
            [DiamondClarity.I2, new Decimal('153')],
            [DiamondClarity.I3, new Decimal('13')],
          ]),
        ],
        [
          DiamondColor.S,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('145')],
            [DiamondClarity.IF, new Decimal('208')],
            [DiamondClarity.VVS1, new Decimal('171')],
            [DiamondClarity.VVS2, new Decimal('212')],
            [DiamondClarity.VS1, new Decimal('33')],
            [DiamondClarity.VS2, new Decimal('255')],
            [DiamondClarity.SI1, new Decimal('41')],
            [DiamondClarity.SI2, new Decimal('15')],
            [DiamondClarity.SI3, new Decimal('92')],
            [DiamondClarity.I1, new Decimal('15')],
            [DiamondClarity.I2, new Decimal('139')],
            [DiamondClarity.I3, new Decimal('199')],
          ]),
        ],
        [
          DiamondColor.T,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('232')],
            [DiamondClarity.IF, new Decimal('32')],
            [DiamondClarity.VVS1, new Decimal('56')],
            [DiamondClarity.VVS2, new Decimal('174')],
            [DiamondClarity.VS1, new Decimal('1')],
            [DiamondClarity.VS2, new Decimal('95')],
            [DiamondClarity.SI1, new Decimal('164')],
            [DiamondClarity.SI2, new Decimal('7')],
            [DiamondClarity.SI3, new Decimal('129')],
            [DiamondClarity.I1, new Decimal('88')],
            [DiamondClarity.I2, new Decimal('221')],
            [DiamondClarity.I3, new Decimal('97')],
          ]),
        ],
        [
          DiamondColor.U,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('127')],
            [DiamondClarity.IF, new Decimal('29')],
            [DiamondClarity.VVS1, new Decimal('155')],
            [DiamondClarity.VVS2, new Decimal('48')],
            [DiamondClarity.VS1, new Decimal('25')],
            [DiamondClarity.VS2, new Decimal('220')],
            [DiamondClarity.SI1, new Decimal('138')],
            [DiamondClarity.SI2, new Decimal('151')],
            [DiamondClarity.SI3, new Decimal('22')],
            [DiamondClarity.I1, new Decimal('76')],
            [DiamondClarity.I2, new Decimal('177')],
            [DiamondClarity.I3, new Decimal('67')],
          ]),
        ],
        [
          DiamondColor.V,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('169')],
            [DiamondClarity.IF, new Decimal('70')],
            [DiamondClarity.VVS1, new Decimal('136')],
            [DiamondClarity.VVS2, new Decimal('208')],
            [DiamondClarity.VS1, new Decimal('73')],
            [DiamondClarity.VS2, new Decimal('214')],
            [DiamondClarity.SI1, new Decimal('84')],
            [DiamondClarity.SI2, new Decimal('85')],
            [DiamondClarity.SI3, new Decimal('179')],
            [DiamondClarity.I1, new Decimal('15')],
            [DiamondClarity.I2, new Decimal('179')],
            [DiamondClarity.I3, new Decimal('78')],
          ]),
        ],
        [
          DiamondColor.W,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('113')],
            [DiamondClarity.IF, new Decimal('26')],
            [DiamondClarity.VVS1, new Decimal('114')],
            [DiamondClarity.VVS2, new Decimal('155')],
            [DiamondClarity.VS1, new Decimal('107')],
            [DiamondClarity.VS2, new Decimal('38')],
            [DiamondClarity.SI1, new Decimal('38')],
            [DiamondClarity.SI2, new Decimal('21')],
            [DiamondClarity.SI3, new Decimal('196')],
            [DiamondClarity.I1, new Decimal('137')],
            [DiamondClarity.I2, new Decimal('101')],
            [DiamondClarity.I3, new Decimal('130')],
          ]),
        ],
        [
          DiamondColor.X,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('144')],
            [DiamondClarity.IF, new Decimal('215')],
            [DiamondClarity.VVS1, new Decimal('161')],
            [DiamondClarity.VVS2, new Decimal('185')],
            [DiamondClarity.VS1, new Decimal('235')],
            [DiamondClarity.VS2, new Decimal('102')],
            [DiamondClarity.SI1, new Decimal('196')],
            [DiamondClarity.SI2, new Decimal('188')],
            [DiamondClarity.SI3, new Decimal('2')],
            [DiamondClarity.I1, new Decimal('38')],
            [DiamondClarity.I2, new Decimal('137')],
            [DiamondClarity.I3, new Decimal('172')],
          ]),
        ],
        [
          DiamondColor.Y,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('128')],
            [DiamondClarity.IF, new Decimal('76')],
            [DiamondClarity.VVS1, new Decimal('89')],
            [DiamondClarity.VVS2, new Decimal('33')],
            [DiamondClarity.VS1, new Decimal('62')],
            [DiamondClarity.VS2, new Decimal('214')],
            [DiamondClarity.SI1, new Decimal('243')],
            [DiamondClarity.SI2, new Decimal('218')],
            [DiamondClarity.SI3, new Decimal('246')],
            [DiamondClarity.I1, new Decimal('245')],
            [DiamondClarity.I2, new Decimal('237')],
            [DiamondClarity.I3, new Decimal('74')],
          ]),
        ],
        [
          DiamondColor.Z,
          new GuardedMap([
            [DiamondClarity.FL, new Decimal('76')],
            [DiamondClarity.IF, new Decimal('162')],
            [DiamondClarity.VVS1, new Decimal('21')],
            [DiamondClarity.VVS2, new Decimal('218')],
            [DiamondClarity.VS1, new Decimal('242')],
            [DiamondClarity.VS2, new Decimal('10')],
            [DiamondClarity.SI1, new Decimal('49')],
            [DiamondClarity.SI2, new Decimal('148')],
            [DiamondClarity.SI3, new Decimal('153')],
            [DiamondClarity.I1, new Decimal('8')],
            [DiamondClarity.I2, new Decimal('136')],
            [DiamondClarity.I3, new Decimal('7')],
          ]),
        ],
      ]),
    },
  ];
}

/**
 * Some mock data generation helpers
 */
/*
 const colors = [
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 ];
 const clarities = [
 'fl',
 'if',
 'vvs1',
 'vvs2',
 'vs1',
 'vs2',
 'si1',
 'si2',
 'si3',
 'i1',
 'i2',
 'I3',
 ];
 let str = 'new GuardedMap([\n';
 for (const color of colors) {
 str += `[DiamondColor.${color.toUpperCase()}, new GuardedMap([\n  `;
 let first = true;
 for (const clarity of clarities) {
 if (!first) {
 str += ',\n  ';
 }
 str += `[DiamondClarity.${clarity.toUpperCase()}, new Decimal('${Math.round(
 Math.random() * 256
 )}')]`;
 first = false;
 }
 str += '\n])],\n';
 }
 str += '\n])';
 console.log(str);

 var str = '[\n';
 var cuts = ["cushion", "radiant", "princess", "asscher", "round", "heart", "triliant", "oval", "pear", "emerald", "marquise", "baguette"];
 for (const cut of cuts) {
 str += `  [DiamondCut.${cut[0].toUpperCase() + cut.slice(1)}, new Decimal('${Math.round(
 Math.random() * 10
 )}')],\n`;
 }
 str += ']';
 console.log(str);
 */
